export const GET_DOCKETS = 'GET_DOCKETS'
export const GET_SHIPTODOCKETS = 'GET_SHIPTODOCKETS'
export const GET_DOCKET_HISTORY = 'GET_DOCKET_HISTORY'
export const GET_THIS_DOCKET = 'GET_THIS_DOCKET'
export const GET_THIS_LANGUAGE = 'GET_THIS_LANGUAGE'
export const GET_GLOBAL_SEARCH_DATA = 'GET_GLOBAL_SEARCH_DATA'




